# Generated by Django 4.1 on 2024-05-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="用户所在院校,可空"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                default="TBD", max_length=8, verbose_name="male/female/TBD"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="self_into",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                default="TBD", max_length=16, verbose_name="recruiter/tutor/TBD"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="TBD", max_length=64),
        ),
        migrations.CreateModel(
            name="public_msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        default="TBD",
                        max_length=16,
                        verbose_name="recruitment/hunt_for_tutor/TBD",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="private_msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FriendList_receiver_id",
                        to="lessons.user",
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FriendList_sender_id",
                        to="lessons.user",
                    ),
                ),
            ],
        ),
    ]
