# Generated by Django 4.1 on 2024-05-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_user_college_user_gender_user_self_into_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="public_msg",
            name="userid",
        ),
        migrations.DeleteModel(
            name="private_msg",
        ),
        migrations.DeleteModel(
            name="public_msg",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
