# Generated by Django 4.1 on 2024-05-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_user_session_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="self_into",
            new_name="self_intro",
        ),
    ]
