# Generated by Django 4.1 on 2024-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_rename_self_into_user_self_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="private_msg",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="public_msg",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="public_msg",
            name="msg_type",
            field=models.CharField(
                default="TBD", max_length=16, verbose_name="家长招聘/老师求聘/TBD"
            ),
        ),
    ]
