# Generated by Django 4.1 on 2024-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_private_msg_content_public_msg_content_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="private_msg",
            new_name="chat_msg",
        ),
        migrations.AddField(
            model_name="user",
            name="avatarUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickName",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="public_msg",
            name="msg_type",
            field=models.CharField(
                default="TBD",
                max_length=16,
                verbose_name="recruitment家长招聘/landjob老师求聘/TBD",
            ),
        ),
    ]
