# Generated by Django 4.1 on 2024-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="openid",
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
