# Generated by Django 4.1 on 2024-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_rename_private_msg_chat_msg_user_avatarurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="public_msg",
            name="msg_type",
            field=models.CharField(
                blank=True,
                max_length=16,
                verbose_name="recruitment家长招聘/landjob老师求聘/TBD",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatarUrl",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="college",
            field=models.CharField(blank=True, max_length=64, verbose_name="用户所在院校,可空"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, max_length=8, verbose_name="male/female/TBD"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickName",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="self_intro",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="recruiter/tutor/TBD"
            ),
        ),
    ]
