# Generated by Django 5.0.6 on 2024-05-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_public_msg_msg_type_alter_user_avatarurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=32),
        ),
    ]
